### PR TITLE
added ping pong example using evothings

### PR DESCRIPTION
**Pull request by storm1er**
https://github.com/sandeepmistry/bleno/issues/280

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Hi @storm1er,

Thanks for taking the time to put this together.

I'd prefer if the Cordova/mobile side was left out of this repo and we'd have an external link to the app in the example. It just keeps things simple for those not using Cordova or who are unfamiliar with it.

Also, for the ping pong example, could we simplify it even further and remove the JSON parsing stuff? Overall, I think the goal of the example is to have a characteristic that stores the data sent on the write request and returns it on the read request right? Maybe renaming it to ReadWrite would be clearer than ping pong?

Thoughts?

**Comment by storm1er** [comment]
Hi @sandeepmistry :)

> I'd prefer if the Cordova/mobile side was left out of this repo and we'd have an external link to the app in the example. It just keeps things simple for those not using Cordova or who are unfamiliar with it.

Well, after spending some time thinking about it, I did this :   
I asked some of my friend & co-workers about example "separated" in != repo, and most of them disagree :    
They prefer getting a full working example in one repo, even on software they don't use then edit code and change software/package as they want, than looking between != repo and find out that there aren't compatible anymore because of some change that could happen in those repo ...   

That's why i didn't do as I said [here](https://github.com/sandeepmistry/bleno/issues/280#issuecomment-292910543) And did a full example in this repo. Feel free to change it, but i'd prefer not.

---

> Also, for the ping pong example, could we simplify it even further and remove the JSON parsing stuff? 

I though that "verbose data transfer" could be more understandable for those who are new to BT APIs.
But as you want ;)

---

> renaming it to ReadWrite would be clearer than ping pong?

(I admit I just said *whatever* when reading this one xD ) 
I commonly see "Ping Pong" for this kind of example, but feel free to rename it if you wish too ;)

**Comment by sandeepmistry** [comment]
So any plans to update this PR with the suggestions above?

**Comment by storm1er** [comment]
Yes, I'm planning to do it but i've been busy on other stuff (well ... *still* busy)
ETA 1 week (June's 4th)

**Comment by sandeepmistry** [comment]
Closing for now due to lacking of activity.

**Pull request closed without merging**
