### PR TITLE
New features: included, secondary services + finer handles control

### PR DESCRIPTION
**Pull request by wino45**
- added include service …
- added secondary service
- added relative and absolute handles (use it with care)
- added example of this features

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@wino45 here's the message id format for OS X peripheral, for the following code: https://github.com/sandeepmistry/osx-ble-peripheral/blob/master/BLEPeripheral/BPAppDelegate.m#L105

```
2015-01-04 11:14:29.920 BLEPeripheral[18451:2380730] sendMsg: 1, {
    kCBMsgArgName = "ca.sandeepmistry.BLEPeripheral";
    kCBMsgArgOptions =     {
        kCBInitOptionShowPowerAlert = 1;
    };
    kCBMsgArgType = 1;
}
2015-01-04 11:14:29.922 BLEPeripheral[18451:2380756] handleMsg: 6, {
    kCBMsgArgState = 5;
}
2015-01-04 11:14:29.922 BLEPeripheral[18451:2380730] peripheralManagerDidUpdateState: 5
2015-01-04 11:14:29.924 BLEPeripheral[18451:2380730] sendMsg: 10, {
    kCBMsgArgAttributeID = 1;
    kCBMsgArgAttributeIDs =     (
    );
    kCBMsgArgCharacteristics =     (
                {
            kCBMsgArgAttributeID = 2;
            kCBMsgArgAttributePermissions = 1;
            kCBMsgArgCharacteristicProperties = 2;
            kCBMsgArgData = <67686f73 74>;
            kCBMsgArgDescriptors =             (
            );
            kCBMsgArgUUID = "Unknown (<a6282ac7 7fca4852 a2e61d69 121fd44a>)";
        }
    );
    kCBMsgArgType = 0;
    kCBMsgArgUUID = "Unknown (<a5b288c3 fc55491f af3827d2 f7d7bf25>)";
}
2015-01-04 11:14:29.925 BLEPeripheral[18451:2380730] sendMsg: 10, {
    kCBMsgArgAttributeID = 3;
    kCBMsgArgAttributeIDs =     (
        1
    );
    kCBMsgArgCharacteristics =     (
                {
            kCBMsgArgAttributeID = 4;
            kCBMsgArgAttributePermissions = 1;
            kCBMsgArgCharacteristicProperties = 2;
            kCBMsgArgData = <7a6f6d62 6965>;
            kCBMsgArgDescriptors =             (
            );
            kCBMsgArgUUID = "Unknown (<ddca9b49 a6f5462f a89ac214 4083ca7f>)";
        }
    );
    kCBMsgArgType = 1;
    kCBMsgArgUUID = "Unknown (<bd0f6577 4a384d71 af1b4e8f 57708080>)";
}
2015-01-04 11:14:29.925 BLEPeripheral[18451:2380756] handleMsg: 18, {
    kCBMsgArgAttributeID = 1;
    kCBMsgArgResult = 0;
}
```

I think it has a similar setup to your Linux patch, where secondary services are referred by id in a primary service.

We will not be able to support relative and absolute handles on OS X.

Another question, how practical is it to have a secondary service included in more than one primary service? I was thinking of a API like:

```javascript
new PrimaryService({
  uuid: '180F',
  included: [
    new SecondaryService({
      uuid: '180E',
      characteristics: [
         // ....
      ]
    })
  ],
  characteristics: [
    new BatteryLevelCharacteristic()
  ]
});
```

That way we don't have to reference included services by id.

**Comment by wino45** [comment]
Hi 
My intentions in modifying Bleno was to add as much flexibility as possible -  everything that is allowed by specification should be do able. This will make Bleno a perfect project to **test** any central device against all possible cases (that is why I miss indication support in Bleno even it is Linux-only).
There is no problem for me with "included: [new SecondaryService({..})]" if both types are supported. I do not like string identifiers either but I have no found way to be fully flexible. IMO the idea of included services are that they are shared between other services -  no matter which ones are primary or secondary.

Sorry for delayed answer, I will try to answer quickly next time.

**Comment by sandeepmistry** [comment]
@wino45 I understand your desired to make bleno as flexible as possible, but one of the projects goals is to have an unified API for both Linux and OS X.

How about passing the included service in by reference:

```javascript

var secondaryService1 = new SecondaryService({
  // ...
});

var secondaryService2 = new SecondaryService({
  // ...
});

var primaryService1 = new PrimaryService({
  // ...
  includeServices: [
    secondaryService1,
    secondaryService2
  ],
  // ...
});

bleno.on('advertisingStart', function(error) {
  console.log('on -> advertisingStart: ' + (error ? 'error ' + error : 'success'));
  if (!error) {
    bleno.setServices([
      primaryService1,
      secondaryService1,
      secondaryService2
    ]);
  }
});

```

This is very similar to the OS X CoreBluetooth API, as well a mix of your proposal and my previous. It eliminates the need for secondary service id's.

**Comment by wino45** [comment]
@sandeepmistry this IMO looks good. 

As of unified API for Linux and OS X. It looks like that Linux is much more flexible then OSX. Maybe you can add some kind of properties with flags what is supported and what is not on particular platform ?
This will allow to write JS code that will be aware of available APIs.

**Comment by sandeepmistry** [comment]
@wino45 I'll add working on OS X side to my todo list, then compare it to your Linux PR, hopefully it gets done in the next few weeks.

I'm thinking about not supporting the relative and absolute handles for initial secondary service API, then we can discuss again later on.

You can distinguish OS via:

```javascript
var os = require('os');

var platform = os.platform();
```

**Comment by sandeepmistry** [comment]
@wino45 see new branch, I've started with OS X, but seems a little unstable with more than one included service:

https://github.com/sandeepmistry/bleno/tree/included-services

**Comment by sandeepmistry** [comment]
This enhancement will cause issues on OS X, closing for now ...

**Pull request closed without merging**
